template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

corsOriginsAllowed: "http://localhost:9000"


server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8444

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    net.ettery: DEBUG

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./application.log
      archivedLogFilenamePattern: ./application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

# the key needs to match the suffix of the renderer
viewRendererConfiguration:
    .ftl:
        strict_syntax: yes
        whitespace_stripping: yes

metrics:
  type: graphite
  frequency: 10s
